name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
        os: [windows-latest, ubuntu-latest, macOS-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1.1.0

      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      # Run for all environments
      - name: Run Tap Tests
        if: github.event_name != 'push' || matrix.node-version != '12.x' || matrix.os != 'ubuntu-latest'
        run: npm test -- --no-coverage

      # Push coverage for specific environment
      - name: Run Tap Tests (push coverage results)
        if: github.event_name == 'push' && matrix.node-version == '12.x' && matrix.os == 'ubuntu-latest'
        run: npm test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
